<a href="https://colab.research.google.com/github/okada-t-rafael/time_series_data_analysis/blob/master/00_NumPy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
mylist = [1, 2, 3]

In [ ]:
type(mylist)

list

In [ ]:
np.array(mylist)

array([1, 2, 3])

In [ ]:
type(mylist)

list

In [ ]:
arr = np.array(mylist)

In [ ]:
arr

array([1, 2, 3])

In [ ]:
mylist = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]

In [ ]:
mylist

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(mylist)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
mymatrix = np.array(mylist)

In [ ]:
mymatrix.shape

(3, 3)

In [ ]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [ ]:
np.zeros((4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones((5, 5)) + 4

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [ ]:
np.ones(4) / 100

array([0.01, 0.01, 0.01, 0.01])

In [ ]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.random.rand(5,5)

array([[0.3247175 , 0.06059803, 0.884543  , 0.96872226, 0.42325779],
       [0.63482582, 0.81557912, 0.2303016 , 0.23917006, 0.83358738],
       [0.17773006, 0.58237671, 0.52165858, 0.83813779, 0.4830309 ],
       [0.60505245, 0.87966568, 0.83015235, 0.34956631, 0.13231081],
       [0.6696313 , 0.03157101, 0.3079177 , 0.2179291 , 0.73587726]])

In [ ]:
np.random.randn(10)

array([ 0.13133004,  0.10295345, -0.1959531 , -0.40083711, -3.0197845 ,
       -0.47735126, -0.11089962,  0.52951046, -0.03522692, -1.69489122])

In [ ]:
# np.random.normal()

In [ ]:
np.random.randint(1, 100, 10)

array([58, 79, 92, 83, 74, 75,  2, 26, 84, 19])

In [ ]:
np.random.seed(555)
np.random.rand(4)

array([0.71783409, 0.04785513, 0.94447198, 0.68638004])

In [ ]:
np.random.rand(4)

array([0.58120733, 0.14267862, 0.94591918, 0.33999059])

In [ ]:
arr = np.arange(25)

In [ ]:
ranarr = np.random.randint(0, 50, 10)

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
ranarr.max()

48

In [ ]:
ranarr.min()

1

In [ ]:
ranarr.argmax()

4

In [ ]:
ranarr.argmin()

6

In [ ]:
ranarr.dtype

dtype('int64')