<a href="https://colab.research.google.com/github/okada-t-rafael/time_series_data_analysis/blob/master/01_NumPy_Indexing_and_Selection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [8]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [9]:
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [10]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [11]:
slice_of_arr = arr[0:6]

In [12]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [13]:
slice_of_arr[:] = 99

In [14]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [15]:
arr_copy = arr.copy()

In [16]:
arr_copy[:] = 10000

In [17]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [18]:
# INDEXING  on 2d array

In [20]:
arr_2d = np.array([[5, 10, 15], [20 ,25, 30], [35, 40, 45]])

In [21]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [22]:
arr_2d.shape

(3, 3)

In [24]:
arr_2d[1][1]

25

In [25]:
arr_2d[1, 1]

25

In [26]:
arr_2d[2, 2]

45

In [32]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [33]:
arr = np.arange(1, 11)

In [34]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [36]:
bool_arr = arr > 4

In [37]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [38]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [39]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [41]:
arr[arr <= 6]

array([1, 2, 3, 4, 5, 6])

In [42]:
arr[arr == 2] = 20

In [43]:
arr

array([ 1, 20,  3,  4,  5,  6,  7,  8,  9, 10])